#!/bin/bash
ABS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source ${ABS_DIR}/bash_user_data_simple
source ${ABS_DIR}/bash_user_data_details

source ${ABS_DIR}/bash_config_vars
