#!/bin/bash

#source bash_data



sed -i "s/address: ''/address: ${SERVER_URL//\//\\/}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/domain: ''/domain: '${SERVER_NAME}'/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/database: ''/database: ${M_TELGM_DB//\//\\/}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/prefix: ''/prefix: \/${M_TELGM_PREFIX}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/external: ''/external: ${M_TELGM_EXTERNAL//\//\\/}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}


sed -i "s/double_puppet_server_map: ''/double_puppet_server_map:\n${M_TELGM_PUPPET_SERVER_MAP//$'\n'/\\n}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/login_shared_secret_map: ''/login_shared_secret_map:\n${M_TELGM_PUPPET_SECRET_MAP//$'\n'/\\n}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/permissions: ''/permissions:\n${M_TELGM_PERMISSIONS//$'\n'/\\n}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/api_id: ''/api_id: ${M_TELGM_API_ID}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/api_hash: ''/api_hash: ${M_TELGM_API_HASH}/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}

sed -i "s/ip: 'M_TELGM_IP_TEST_SERVER'/ip: '${M_TELGM_IP_TEST_SERVER}'/" ${MAUTRIX_TELEGRAM_LOCAL_FOLDER}config.yaml-${FINAL_RC}


