#FROM postgres:10-alpine
#FROM postgres:10-bullseye
FROM postgres:14-bullseye
#RUN apt-get update
#RUN apt-get install -y locales locales-all
#RUN localedef -i C -c -f UTF-8 -A /usr/share/locale/locale.alias C.UTF-8
#ENV LANG C.UTF-8
#ENV LC_ALL C.UTF-8
